{
 "title": "GoodsPriceCalculator Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "File Processing Started Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "file_processing_started_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "File Processing Average Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "file_processing_duration_seconds_sum/file_processing_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantity Calculation Started Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantity_calculation_started_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Quantity Calculation Average Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantity_calculation_duration_seconds_sum / quantity_calculation_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Price Calculation Started Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "price_calculation_started_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Price Calculation Average Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "price_calculation_duration_seconds_sum / price_calculation_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}