receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:8889
    send_timestamps: true
service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
